#!/usr/bin/env python
import sys
from crew_automation_for_erp_research_and_outreach.crew import CrewAutomationForErpResearchAndOutreachCrew

# This main file is intended to be a way for your to run your
# crew locally, so refrain from adding unnecessary logic into this file.
# Replace with inputs you want to test with, it will automatically
# interpolate any tasks and agents information

def run():
    """
    Run the crew.
    """
    inputs = {
        'company_name': 'ARDAGH METAL PACKAGING FRANCE',
        'siren': '820885531',
        'city': 'LA CIOTAT',
        'activity_type': 'Fabrication d emballages métalliques légers',
        'website_url': 'https://www.ardaghmetalpackaging.com/',
        'our_product': 'ERP Sage X3 and YouDoc by Sage',
    }

    CrewAutomationForErpResearchAndOutreachCrew().crew().kickoff(inputs=inputs)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: main.py <command> [<args>]")
        sys.exit(1)

    command = sys.argv[1]
    if command == "run":
        run()

    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
